name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: swr.ru-moscow-1.hc.sbercloud.ru
          username: ${{ secrets.SBER_CLOUD_USER }}
          password: ${{ secrets.SBER_CLOUD_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file assets/Dockerfile --tag swr.ru-moscow-1.hc.sbercloud.ru/${{ secrets.SBER_CLOUD_REPOSITORY_USER }}/werther:latest
      - name: Push image
        run: docker push swr.ru-moscow-1.hc.sbercloud.ru/${{ secrets.SBER_CLOUD_REPOSITORY_USER }}/werther:latest
